cargo-features = ["profile-rustflags"]

[package]
name = "cawlr"
version = "0.1.0"
edition = "2021"
authors = ["Brandon Saint-John <bsaintjo@ucsc.edu>"]
readme = "README.md"
description = "calwr: Chromatin accessibility with long reads"
license = "BSD-3-Clause"
categories = ["science", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
bio = "0.39.2"
bio-types = "0.12.1"
clap = { version = "3.1.1", features = ["derive"] }
criterion-stats = "0.3.0"
csv = "1.1.6"
env_logger = "0.9.0"
fnv = "1.0.7"
indicatif = { version = "0.16.2", features = ["rayon", "improved_unicode"] }
itertools = "0.10.3"
linfa = { version = "0.5.0", features=["openblas-static"] }
linfa-clustering = { version = "0.5.0", features=["serde"] }
log = "0.4.14"
mimalloc = { version = "0.1.28", default-features = false, optional = true }
ndarray = "0.15.4"
parquet = { version = "8.0.0", default-features = false, features=["arrow", "base64"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rstats = "1.0.13"
rust-htslib = { version = "0.38.2", default-features = false }
rv = { version = "0.14.3", features = ["serde1"] }
serde = "1.0.136"
serde-pickle = "1.1.0"
serde_arrow = "0.4.0"
serde_with = "1.12.0"
xxhash-rust = { version = "0.8.4", features = ["xxh64"] }

[profile.release]
lto = true
rustflags = ["-C", "target-cpu=native"]

[profile.test]
opt-level = 3

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
test-log = "0.2.10"
escargot = "0.5.7"

[features]
default = ["mimalloc"]
alloc = []