name: "Build with musl binary"
on:
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        run: docker build -t local <dockerfiles/musl.Dockerfile
      - name: compile static binary
        run: docker run \
          --rm -it \
          -u "$(id -u)":"$(id -g)" \
          -e RUSTFLAGS="-C target-feature=+crt-static" \
          -v "$(pwd)":/src local \
          cargo build --release --workspace --target x86_64-unknown-linux-musl