name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Install MUSL tools
        run: sudo apt-get install -y pkg-config musl-tools

      - name: Checkout main
        uses: actions/checkout@v2

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
        run: rustup target add x86_64-unknown-linux-musl

      - name: Compile
        run: cargo build --target x86_64-unknown-linux-musl --bin cawlr --release --locked
        env:
          RUSTFLAGS: -C target-feature=+crt-static

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: cawlr
          file: target/release/cawlr
