name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Compile
        run: cargo build --bin cawlr --release --locked

      # - name: Run cargo build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --bin cawlr --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: cawlr-linux-x86_64
          file: target/release/cawlr
