name: Publish CentOS 7 binary

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  RELEASE_BINARY: target/x86_64-unknown-linux-gnu/release/cawlr
  DIST_DIR: cawlr-${{ github.ref_name }}/
  COMPRESSED: cawlr-${{ github.ref_name }}-x86_64-centos-linux-gnu.tar.gz

jobs:
  centos7:
    name: Compile and upload release binary
    runs-on: ubuntu-latest
    container: "centos:7"

    steps:
      - name: Install build dependencies
        run: |
          yum -y install epel-release
          yum -y install make gcc gcc-gfortran perl openblas-devel

      - name: Checkout main
        uses: actions/checkout@v2

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu --locked
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary and create archive
        run: |
          strip ${{ env.RELEASE_BINARY }}
          mkdir ${{ env.DIST_DIR }}
          cp README.md LICENSE ${{ env.RELEASE_BINARY }} ${{ env.DIST_DIR }}
          tar -cvzf ${{ env.COMPRESSED }} ${{ env.DIST_DIR }}

      - name: Upload binaries to release
        if: ${{ github.ref != 'refs/heads/main'}}
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.COMPRESSED }}
          overwrite: true
